kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.incloudsphere.inspur.com
allowVolumeExpansion: true
parameters:
  datastoreurl: "8a878bda6f6f3ca4016f6f458b50003c"
  fstype: "ext4" 
