kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.incloudsphere.inspur.com
allowVolumeExpansion: true
parameters:
  datastoreurl: "8ab0b28d77be994a0177bea19e1d0078"
  fstype: "ext4" 
