kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-block-sc-zone
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.icsphere.inspur.com
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - k8s-zone-1
      - key: failure-domain.beta.kubernetes.io/region
        values:
          - k8s-region-test
