apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-block-pvc-zone
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: example-block-sc-zone
