apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-cfs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: example-cfs-zone
