kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-sc-zone-wfc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.incloudsphere.inspur.com
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - k8s-zone-1
      - key: failure-domain.beta.kubernetes.io/region
        values:
          - k8s-region-test
